### ISSUE TITLE
How to segment/wrap?

### ISSUE THREAD

**Issue by fileweb3serve** [EdJoPaTo/telegram-format#41]
How to segment/wrap?
\Both n and<br>have no effect

**Comment by EdJoPaTo** [comment]
I am not sure what your question is. This library helps with the [Formatting Options on the Bot API documentation page](https://core.telegram.org/bots/api#formatting-options) so it only does what's possible there.

**Comment by EdJoPaTo** [comment]
Due to inactivity I'll close this. Feel free to reopen when the question/issue still persist.
