### ISSUE TITLE
Bad Request: can't parse entities

### ISSUE THREAD

**Issue by joeyave** [EdJoPaTo/telegram-format#5]
Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\'

**Comment by EdJoPaTo** [comment]
I assume you are referencing `MarkdownV2`? You have to use the `format.escape(input)` function to make sure your text is displayable for Telegram.

Personally I think MarkdownV2 (and Markdown) are a bit annoying to use and like to use HTML with this library as it is the simplest of the 3 while having all the features available.

**Comment by joeyave** [comment]
I've used `format.escape(input)`.

**Comment by EdJoPaTo** [comment]
Can you provide a small example in which case it does not work?

**Comment by EdJoPaTo** [comment]
I'll just close this due to inactivity. If you have any questions feel free to ask ahead!
